version: '3'

services:
  web: &web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db/everycheese
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: everycheese
    volumes:
      - ${LOCAL_VOLUME}:/var/lib/postgresql/data
