# Generated by Django 3.0.8 on 2020-07-17 18:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [("cheeses", "0002_auto_20200716_2206")]

    operations = [
        migrations.AddField(
            model_name="cheese",
            name="country_of_origin",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, verbose_name="Country of Origin"
            ),
        )
    ]
